#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export AI_DISPATCH_ACCEPTANCE_TARGET="${AI_DISPATCH_ACCEPTANCE_TARGET:-grok}"
export AI_DISPATCH_ACCEPTANCE_PROVIDER="${AI_DISPATCH_ACCEPTANCE_PROVIDER:-grok}"
export AI_DISPATCH_ACCEPTANCE_MODEL="${AI_DISPATCH_ACCEPTANCE_MODEL:-grok-4.5}"
export AI_DISPATCH_ACCEPTANCE_VARIANT_TARGET="${AI_DISPATCH_ACCEPTANCE_VARIANT_TARGET:-grok-fast}"
export AI_DISPATCH_ACCEPTANCE_VARIANT_MODEL="${AI_DISPATCH_ACCEPTANCE_VARIANT_MODEL:-grok-composer-2.5-fast}"
export AI_DISPATCH_ACCEPTANCE_PROVIDER_OPTS="${AI_DISPATCH_ACCEPTANCE_PROVIDER_OPTS:-grok.max-turns=1,grok.web-search=off,grok.subagents=off}"
export AI_DISPATCH_ACCEPTANCE_TOOL_PROVIDER_OPTS="${AI_DISPATCH_ACCEPTANCE_TOOL_PROVIDER_OPTS:-grok.max-turns=3,grok.web-search=off,grok.subagents=off}"
export AI_DISPATCH_ACCEPTANCE_FALLBACK_ENV="${AI_DISPATCH_ACCEPTANCE_FALLBACK_ENV:-AI_DISPATCH_GROK_BIN}"
export AI_DISPATCH_ACCEPTANCE_FALLBACK_PROVIDER="${AI_DISPATCH_ACCEPTANCE_FALLBACK_PROVIDER:-opencode}"
export AI_DISPATCH_ACCEPTANCE_FALLBACK_MODEL="${AI_DISPATCH_ACCEPTANCE_FALLBACK_MODEL:-openrouter/x-ai/grok-4.5}"
export AI_DISPATCH_ACCEPTANCE_INVALID_PROVIDER_OPT="${AI_DISPATCH_ACCEPTANCE_INVALID_PROVIDER_OPT:-grok.max-turns=0}"
export AI_DISPATCH_ACCEPTANCE_INVALID_MODEL="${AI_DISPATCH_ACCEPTANCE_INVALID_MODEL:-openrouter/x-ai/grok-4.5}"
export AI_DISPATCH_ACCEPTANCE_UNSUPPORTED_TARGETS="${AI_DISPATCH_ACCEPTANCE_UNSUPPORTED_TARGETS:-grok-build-0.1}"
export AI_DISPATCH_ACCEPTANCE_TASK_PREFIX="${AI_DISPATCH_ACCEPTANCE_TASK_PREFIX:-grok-stress}"

exec "$ROOT/scripts/go_provider_acceptance.sh"
